platform :ios, '18.0'

project 'TinyCloudMusicIOS.xcodeproj'

target 'TinyCloudMusicIOS' do
  pod 'NIMSDK_LITE/NOS', '10.9.40'

  target 'TinyCloudMusicIOSTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
